# -*- coding: utf-8 -*-
"""
utils/logging_setup.py
======================
Centralized logging configuration for the CogniX Algo platform.

Configures the ROOT logger once at application startup with two handlers:

1. Console (stdout)
   - Useful during local development.
   - Also captured automatically when running under systemd, Docker, PM2,
     or other process managers.

2. Daily rotating log file
   - Every log entry generated by the platform (including TradingEngine,
     Broker, Strategy, WebSocket, API, and per-symbol logs) is written to:

         logs/cognix_algo.log

   - Rotates automatically at midnight.
   - Retains the last 7 days of log history.

The dashboard's in-memory log buffer is intended only for live monitoring.
The rotating log file serves as the permanent audit/debug history and
persists across application restarts or unexpected crashes.
"""

import logging
import os
from logging.handlers import TimedRotatingFileHandler

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG_DIR = os.path.join(BASE_DIR, "logs")


def configure_logging(level=logging.INFO, backup_days=7):
    """Configure application-wide logging."""

    os.makedirs(LOG_DIR, exist_ok=True)

    fmt = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s"
    )

    root = logging.getLogger()
    root.setLevel(level)

    # Prevent duplicate handlers after reloads/restarts
    root.handlers.clear()

    # Console output
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(fmt)
    root.addHandler(console_handler)

    # Daily rotating log file
    logfile = os.path.join(LOG_DIR, "cognix_algo.log")

    file_handler = TimedRotatingFileHandler(
        filename=logfile,
        when="midnight",
        backupCount=backup_days,
        encoding="utf-8",
        utc=False,
    )
    file_handler.setFormatter(fmt)
    file_handler.suffix = "%Y-%m-%d"

    root.addHandler(file_handler)

    logging.info(
        "📝 Logging configured — console + %s (rotated daily, %s days kept)",
        logfile,
        backup_days,
    )

    return root